steps:
  # Build your container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/shopping-list', '.']
  # Push the container image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/shopping-list']
  # Deploy the container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'saleslist'
      - '--image'
      - 'gcr.io/shopping-list'
      - '--platform'
      - 'managed'
      # Add other deployment options if needed, e.g., --region, --allow-unauthenticated, etc.
